# Generated by Django 6.1.1 on 2026-10-06 07:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0002_user_salary'),
    ]

    operations = [
        migrations.CreateModel(
            name='KpiTarget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monthly_revenue_target', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('monthly_orders_target', models.DecimalField(decimal_places=1, default=0, max_digits=6)),
                ('availability_target', models.PositiveSmallIntegerField(default=90)),
                ('bonus_rate', models.PositiveSmallIntegerField(default=20)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='kpi_target', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
